In [2]:
import numpy as np
import tensorflow as tf

## Rank 0
Scalar

In [20]:
mammal = tf.Variable('Cat', tf.string)
integer = tf.Variable(451, tf.int16)
pi = tf.Variable(3.1415926, tf.float64)
its_complicated = tf.Variable(12.3-4.85j, tf.complex64)
its_complicated

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>

## Rank 1
vector

In [21]:
mystr = tf.Variable(['Hello'], tf.string)
cool_nums = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2,3,5,7,11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)
first_primes

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>

## Higher Ranks
a rank 2 `tf.Tensor` objects consists of at least 1 row and 1 column

In [36]:
mymat = tf.Variable([[7], [11]], tf.int16)
print(mymat)
xor = tf.Variable([[False, True],[True, False]], tf.bool)
print(xor)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
print(squarish_squares)
print(squarish_squares.shape)

rank_of_squares = tf.rank(squarish_squares)
print(rank_of_squares)
print(rank_of_squares.shape)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>
(2, 2)
tf.Tensor(2, shape=(), dtype=int32)
()


In [37]:
# batch x height x width x color
my_img = tf.zeros([10, 299, 299, 3])
print(my_img.shape)
print(tf.rank(my_img)) 
# tf.Tensor(4, shape=(), dtype=int32)
# rank 4

(10, 299, 299, 3)
tf.Tensor(4, shape=(), dtype=int32)


## Access Tensor

In [50]:
my_vector = tf.Variable(range(1,6), tf.int32)
print(my_vector)
# for a ran 1 tensor, passing a single index to access the value
my_scalar = my_vector[2]
print(my_scalar)
print(my_scalar==3)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(True, shape=(), dtype=bool)


In [61]:
my_mat = tf.Variable([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], tf.int32)
my_scalar = my_mat[1,2]
print(my_scalar)

my_row_vector = my_mat[2]
print(my_row_vector)

my_col_vector = my_mat[:,2]
print(my_col_vector)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


## Shape

In [62]:
# create a vector of zeros with the # of columns in a given matrix
zeros = tf.zeros(my_mat.shape[1], tf.int32)
zeros

<tf.Tensor: id=608, shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [63]:
# 4 x 3 matrix
my_mat.shape

TensorShape([4, 3])

## Changing the shape of a `tf.Tensor`

In [73]:
rank_3_tensor = tf.ones([3,4,5])
print(rank_3_tensor.shape)

mat_a = tf.reshape(rank_3_tensor, [6,10])
print(mat.shape)

# -1 indicates reshape to calculate the size of dimension
mat_b = tf.reshape(mat_a, [3,-1])
print(mat_b.shape)

mat_c = tf.reshape(rank_3_tensor, [4,3,-1])
print(mat_c.shape)

(3, 4, 5)
(6, 10)
(3, 20)
(4, 3, 5)


## Evaluate tensors

In [78]:
constant = tf.constant([1, 2, 3])
tensor = constant * constant
print(tensor.numpy())

[1 4 9]


## Expand dimensions

In [87]:
my_mat = tf.Variable([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], tf.int32)
print('mat')
print(my_mat.shape)

print('mat1')
new_mat = tf.expand_dims(my_mat, 0)
print(new_mat.shape)
print(new_mat.numpy())

print('mat2')
new_mat2 = tf.expand_dims(my_mat, 1)
print(new_mat2.shape)
print(new_mat2.numpy())

print('mat3')
new_mat3 = tf.expand_dims(my_mat, -1)
print(new_mat3.shape)
print(new_mat3.numpy())

mat
(4, 3)
mat1
(1, 4, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
mat2
(4, 1, 3)
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
mat3
(4, 3, 1)
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
